# Generated by Django 4.0 on 2022-01-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_name_user_zjh_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='zjh_login_user',
        ),
    ]
