# Generated by Django 2.2.24 on 2022-01-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20220113_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zjh_name', models.CharField(max_length=128, unique=True)),
                ('zjh_target', models.CharField(max_length=256)),
                ('zjh_method', models.CharField(max_length=10)),
                ('zjh_result', models.CharField(max_length=1024)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'zjh_history',
                'ordering': ['c_time'],
            },
        ),
    ]
