# Generated by Django 2.2.24 on 2022-01-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20220114_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='zjh_name',
            field=models.CharField(max_length=128),
        ),
    ]
