# Generated by Django 2.2.24 on 2022-01-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20220114_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='zjh_dic',
            field=models.CharField(max_length=1024),
        ),
    ]
