# Generated by Django 2.2.24 on 2022-01-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20220114_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='zjh_dic',
            field=models.CharField(max_length=10240),
        ),
    ]
